### ISSUE TITLE
(1.5.2) IC2 crops visual bug

### ISSUE THREAD

**Issue by Pyromanc3r** [VintageModsReforged/BlockHelperAddons#6]
The BlockHelper info panel flickers when crosshairing over some IC2 plants. It is trying to display different drops at the same time.
The following IC2 crops are not displayed correctly:

Withereed
Melon
Enderbloom
Meatrose
Bobsyeruncleranks
Diareed
Blazereed
Eggplant
Corpseplant
Spidernip

**Comment by CrossVas** [comment]
To give a little more information.

## Problem
IC2 crops drop items randomly on each harvest. Since we call rendering function every tick, the drop is updated accordingly, then displayed, resulting in constant change. 

## Solution
Provide a list of possible drop items and display one item for a fixed interval (1 second). This ensures a stable and consistent representation of the crop's drop list.

## Drop display
**IC2 Crops:** Use the provided list of drop items, updating the display every second.
**GregTech Items:** Use vanilla items (like diamonds and emeralds) as substitutes because accessing GregTech's internals is complex.
